name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/cloudops-employee-portal || git clone https://github.com/tarfi786/cloudops-employee-portal.git
          cd cloudops-employee-portal
          git pull origin main
          pip3 install -r requirements.txt
          sudo systemctl restart gunicorn || true
